"""
Downstream model training package for EEG seizure detection.

Trains 4 independent models on spike-encoded SNN features (.npz files)
generated by the spike_pipeline:

    1. Autoencoder     — unsupervised anomaly detection
    2. LSTM            — sequential classification on latent vectors
    3. CNN             — 1D convolution on spike feature maps
    4. Transformer     — multi-head attention classification

Each model can be trained standalone via its own script, or orchestrated
via the ensemble runner.
"""
